on:
  push:
    branches-ignore:
    - 'master'
    tags-ignore:
    - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Verify dependencies
        run: go mod verify
      - name: Verify that code already formated
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      - name: Run go vet
        run: go vet ./...
  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: Run tests
        run: go test -v
